-- Tạo DB (đổi tên nếu cần)
CREATE DATABASE IF NOT EXISTS sat_hsa CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE sat_hsa;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('admin','student') NOT NULL DEFAULT 'student',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tests (đề thi)
CREATE TABLE IF NOT EXISTS tests (
  id INT NOT NULL AUTO_INCREMENT,
  mode ENUM('adaptive','fixed','diagnostic') NOT NULL DEFAULT 'fixed',
  title VARCHAR(255) NOT NULL,
  durationSec INT NOT NULL DEFAULT 3600,
  quantities INT NOT NULL DEFAULT 0,
  startedAt DATETIME NULL,
  endedAt DATETIME NULL,
  userId INT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_tests_userId (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Questions
CREATE TABLE IF NOT EXISTS questions (
  id INT NOT NULL AUTO_INCREMENT,
  hashId VARCHAR(255) NULL,
  content TEXT NOT NULL,
  section VARCHAR(255) NULL,
  skill VARCHAR(255) NULL,
  passage TEXT NULL,
  difficulty VARCHAR(255) NULL,
  model VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Question choices
CREATE TABLE IF NOT EXISTS questionchoices (
  id INT NOT NULL AUTO_INCREMENT,
  choiceText TEXT NOT NULL,
  isCorrect TINYINT(1) NOT NULL DEFAULT 0,
  questionId INT NOT NULL,
  choiceOrder INT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_qc_questionId (questionId),
  CONSTRAINT fk_qc_question FOREIGN KEY (questionId) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Test-Questions
CREATE TABLE IF NOT EXISTS test_questions (
  id INT NOT NULL AUTO_INCREMENT,
  testId INT NOT NULL,
  questionId INT NOT NULL,
  `order` INT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_test_question (testId, questionId),
  KEY idx_tq_testId (`testId`),
  KEY idx_tq_questionId (`questionId`),
  CONSTRAINT fk_tq_test FOREIGN KEY (testId) REFERENCES tests(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tq_question FOREIGN KEY (questionId) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Exam attempts (History)
CREATE TABLE IF NOT EXISTS exam_attempts (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  testId INT NOT NULL,
  status ENUM('completed','in_progress') NOT NULL DEFAULT 'completed',
  startedAt DATETIME NULL,
  submittedAt DATETIME NULL,
  durationSec INT NULL,
  correctCount INT NOT NULL DEFAULT 0,
  totalQuestions INT NOT NULL DEFAULT 0,
  score INT NOT NULL DEFAULT 0,
  totalScore INT NOT NULL DEFAULT 800,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_attempt_user (userId),
  KEY idx_attempt_test (testId),
  CONSTRAINT fk_attempt_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_attempt_test FOREIGN KEY (testId) REFERENCES tests(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS exam_attempt_answers (
  id INT NOT NULL AUTO_INCREMENT,
  attemptId INT NOT NULL,
  questionId INT NOT NULL,
  selectedChoiceId INT NULL,
  isCorrect TINYINT(1) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ans_attempt (attemptId),
  KEY idx_ans_question (questionId),
  KEY idx_ans_choice (selectedChoiceId),
  CONSTRAINT fk_ans_attempt FOREIGN KEY (attemptId) REFERENCES exam_attempts(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ans_question FOREIGN KEY (questionId) REFERENCES questions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ans_choice FOREIGN KEY (selectedChoiceId) REFERENCES questionchoices(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
